### ISSUE TITLE
report: jet engines are audible ahead of the mach cone

### ISSUE THREAD

**Issue by JonnyOThan** [KSPModStewards/RocketSoundEnhancement#32] opened 2024-08-19 13:29 UTC
> Hello, I think for some reason some engines like jet and srbs aren't affected by airsim and muffler effects(like you can still hear jet engine in forward of aircraft past mach speed, or srb way too loud for vacuum)
[KSP (22).zip](https://github.com/user-attachments/files/16660841/KSP.22.zip)

**Comment by likeproblem** [comment] 2024-09-10 23:43
It's me, original author of the issue, I found sorta solution. For some unknown reason, the Waterfall Patch doesn't remove jet engine sounds(including rapier air breathing).
The solution was to do the same thing is done to the parts in the Patch
Im still working to get srb work the same way

When Im done Im going to publish little patch here

**Comment by likeproblem** [comment] 2024-09-10 23:54
The issue is just stock sounds(maybe not so stock, swe and restock definitely had a hand) not being deleted
Correlates to this issue right here: https://github.com/KSPModStewards/RocketSoundEnhancementDefault/issues/5

**Comment by likeproblem** [comment] 2024-09-12 00:10
[RSEFixes.cfg.txt](https://github.com/user-attachments/files/16971643/RSEFixes.cfg.txt)
here it is
SRBs still act weird, sometimes mute, sometimes not, but good enough

**Comment by likeproblem** [comment] 2024-09-14 03:19
Update: Found new issue and fixed it, found out to be issues with SWE, which has WaterfallRestock replacements, which in fact use MM's LAST, so I had to do the same thing to override it(those six engines were mentioned here, https://github.com/KSPModStewards/RocketSoundEnhancementDefault/issues/5,  thanks ArgentGamer)
[RSEFixes.cfg.txt](https://github.com/user-attachments/files/17000755/RSEFixes.cfg.txt)

**Comment by likeproblem** [comment] 2024-09-24 22:06
@JonnyOThan close this as fixes are made and merged into Default Config

**Closed** 2024-09-24 23:32 UTC
Labels: bug
